# Generated by Django 2.2.13 on 2020-06-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='company', max_length=200)),
                ('title', models.CharField(default='Intern', max_length=200)),
                ('description', models.TextField(default='desc')),
                ('location', models.CharField(default='place, place', max_length=200)),
                ('work_period', models.CharField(default='date - date', max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Involvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='involvement', max_length=200)),
                ('role', models.CharField(default='member', max_length=200)),
                ('description', models.TextField(default='desc')),
                ('work_period', models.CharField(default='date - date', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='project', max_length=200)),
                ('description', models.TextField(default='desc')),
                ('work_period', models.CharField(default='date - date', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='skill', max_length=200)),
                ('experienced', models.BooleanField(default='False')),
                ('level', models.IntegerField(default='0')),
            ],
        ),
    ]
